### ISSUE TITLE
Redmine 3.0 support (Rails 4.2)

### ISSUE THREAD

**Issue by frol** [Hopebaytech/redmine_issue_reminder#12]
**Disclaimer: I'm not a Ruby developer, so I don't create a pull request, but my solution works for me!**

Since Redmine 3.0 moved on RoR 4.2 there are some changes that has to be applied in redmine_issue_reminder:

1. `.find_all_by_*` is deprecated in RoR 4.0 and is completely removed in 4.2
1. Mass-assignment model attributes has to be addressed via strong parameters to avoid security issues

```diff
diff --git a/app/controllers/issue_reminders_controller.rb b/app/controllers/issue_reminders_controller.rb 
index 8a91a99..d3b31fe 100644 
--- a/app/controllers/issue_reminders_controller.rb 
+++ b/app/controllers/issue_reminders_controller.rb 
@@ -6,20 +6,21 @@ class IssueRemindersController < ApplicationController 
  
   def index 
     needs_refresh = false 
-    @reminders = IssueReminder.find_all_by_project_id(@project) 
+    @reminders = IssueReminder.where(project_id: @project) 
     @reminders.each do |reminder| 
       if reminder.query.nil? 
         reminder.destroy 
         needs_refresh = true 
       end 
     end 
-    @reminders = IssueReminder.find_all_by_project_id(@project) if needs_refresh 
+    @reminders = IssueReminder.where(project_id: @project) if needs_refresh 
      
     @reminder = IssueReminder.new 
   end 
  
   def create 
-    reminder = IssueReminder.new(params[:reminder]) 
+    parameters = ActionController::Parameters.new(params[:reminder]) 
+    reminder = IssueReminder.new(parameters.permit(:project_id, :query_id, :interval)) 
     reminder.interval_value = params[:interval_value].to_i 
     if reminder.save 
       Role.find_all_givable.each do |role| 
diff --git a/app/models/issue_reminder.rb b/app/models/issue_reminder.rb 
index a405c8f..5882b64 100644 
--- a/app/models/issue_reminder.rb 
+++ b/app/models/issue_reminder.rb 
@@ -1,6 +1,7 @@ 
 require "date"
 
 class IssueReminder < ActiveRecord::Base
+  include ActiveModel::ForbiddenAttributesProtection
   unloadable
 
   WEEKLY_INTERVAS = Date::DAYNAMES
@@ -102,4 +103,6 @@ class IssueReminder < ActiveRecord::Base
       return Time.now.mday == interval_value
     end
   end
+
+  attr_accessible :project_id, :query_id, :interval
 end
```

One more thing is to use RoR 4.2 compatible `prototype-rails`:

```bash
$ gem install specific_install
$ gem specific_install -l https://github.com/rails/prototype-rails.git -b 4.2
```

**Comment by Androc** [comment]
Did you have problems with other plugins ? I wonder if it is worth to upgrade to Redmine 3.0.

Could you tell me which plugins you use and if you have problems or no problems for each of your plugins ?

**Comment by frol** [comment]
It is the only plugin that I have.

**Comment by Androc** [comment]
Ah ok. Is it intended or do you want suggestions for other usefull plugins ?

**Comment by frol** [comment]
I don't feel like I need anything extra at this point. I was absolutely happy with Redmine out-of-the-box until my team realized that we missed a lot of issues in idle (inactive) state.

**Comment by jcppkkk** [comment]
maybe create a 2.6 branch and bump up master to Redmine 3.0 / RoR 4.2 ? However, the extra effort to cherry-pick common patches around branch 2.6/3.0 is needed. 

I also stick with 2.6 currently. Migrating to Redmine 3.0 is a great pain that plugins i am using are broken in RoR 4.2 and need a lot of work to fix them.

**Comment by frol** [comment]
@jcppkkk I'm not 100% sure, but it seems to me that my changes are compatible with Redmine 2.6 and older.

**Comment by Androc** [comment]
@jcppkkk which plugins do you use and are broken in 3.0 ?

**Comment by jcppkkk** [comment]
@Androc errors are mostly from Scrum plugin http://www.redmine.org/plugins/scrum-plugin . It's a must-have feature for our team.

**Comment by Androc** [comment]
Oh I see. I installed it too but do not really use it at the moment.

**Comment by jcppkkk** [comment]
Created 2.6 branch and bump up master to Redmine 3.0 / RoR 4.2. Please see changes from d5350f9c1af030443ec0fb4c2b7e1e2ce77cb998. Need to ```bundle install``` after pull.
@frol, you may close this issue if there are no errors on Redmine 3.0

**Comment by frol** [comment]
@jcppkkk Thank you! I've commented one little note to the commit, but it is not critical, just cleaning up. I'm closing the issue.
