### ISSUE TITLE
NameError (uninitialized constant ActiveModel::ForbiddenAttributesProtection)

### ISSUE THREAD

**Issue by Eric06** [Hopebaytech/redmine_issue_reminder#17]
Hi
I have installed the plug-in without any trouble.
I activated Issue reminder module on one project.
When i Cliqued on Issue reminder Tab, i have an Internal Error.
The log file contains following information 
NameError (uninitialized constant ActiveModel::ForbiddenAttributesProtection):
  plugins/redmine_issue_reminder/app/models/issue_reminder.rb:4:in `<class:IssueReminder>'
  plugins/redmine_issue_reminder/app/models/issue_reminder.rb:3:in `<top (required)>'
  plugins/redmine_issue_reminder/app/controllers/issue_reminders_controller.rb:9:in `index'
  actionpack (3.2.19) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (3.2.19) lib/abstract_controller/base.rb:167:in `process_action'
  actionpack (3.2.19) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (3.2.19) lib/abstract_controller/callbacks.rb:18:in `block in process_action'
  activesupport (3.2.19) lib/active_support/callbacks.rb:491:in `_run__991194143456878048__process_action__3551702885271858478__callbacks'
  activesupport (3.2.19) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.19) lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
  activesupport (3.2.19) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.19) lib/abstract_controller/callbacks.rb:17:in `process_action'
  actionpack (3.2.19) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (3.2.19) lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
  activesupport (3.2.19) lib/active_support/notifications.rb:123:in `block in instrument'
  activesupport (3.2.19) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (3.2.19) lib/active_support/notifications.rb:123:in `instrument'
  actionpack (3.2.19) lib/action_controller/metal/instrumentation.rb:29:in `process_action'
  actionpack (3.2.19) lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
  activerecord (3.2.19) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (3.2.19) lib/abstract_controller/base.rb:121:in `process'
  actionpack (3.2.19) lib/abstract_controller/rendering.rb:45:in `process'
  actionpack (3.2.19) lib/action_controller/metal.rb:203:in `dispatch'
  actionpack (3.2.19) lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
  actionpack (3.2.19) lib/action_controller/metal.rb:246:in `block in action'
  actionpack (3.2.19) lib/action_dispatch/routing/route_set.rb:73:in `call'
  actionpack (3.2.19) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
  actionpack (3.2.19) lib/action_dispatch/routing/route_set.rb:36:in `call'
  journey (1.0.4) lib/journey/router.rb:68:in `block in call'
  journey (1.0.4) lib/journey/router.rb:56:in `each'
  journey (1.0.4) lib/journey/router.rb:56:in `call'
  actionpack (3.2.19) lib/action_dispatch/routing/route_set.rb:608:in `call'
  rack-openid (1.4.2) lib/rack/openid.rb:98:in `call'
  actionpack (3.2.19) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
  rack (1.4.5) lib/rack/etag.rb:23:in `call'
  rack (1.4.5) lib/rack/conditionalget.rb:25:in `call'
  actionpack (3.2.19) lib/action_dispatch/middleware/head.rb:14:in `call'
  actionpack (3.2.19) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
  actionpack (3.2.19) lib/action_dispatch/middleware/flash.rb:242:in `call'
  rack (1.4.5) lib/rack/session/abstract/id.rb:210:in `context'
  rack (1.4.5) lib/rack/session/abstract/id.rb:205:in `call'
  actionpack (3.2.19) lib/action_dispatch/middleware/cookies.rb:341:in `call'
  activerecord (3.2.19) lib/active_record/query_cache.rb:64:in `call'
  activerecord (3.2.19) lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
  actionpack (3.2.19) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
  activesupport (3.2.19) lib/active_support/callbacks.rb:405:in `_run__3107019785361985223__call__2382551962215304565__callbacks'
  activesupport (3.2.19) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.19) lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
  activesupport (3.2.19) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.19) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (3.2.19) lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
  actionpack (3.2.19) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
  actionpack (3.2.19) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
  railties (3.2.19) lib/rails/rack/logger.rb:32:in `call_app'
  railties (3.2.19) lib/rails/rack/logger.rb:18:in `call'
  actionpack (3.2.19) lib/action_dispatch/middleware/request_id.rb:22:in `call'
  rack (1.4.5) lib/rack/methodoverride.rb:21:in `call'
  rack (1.4.5) lib/rack/runtime.rb:17:in `call'
activesupport (3.2.19) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
  rack (1.4.5) lib/rack/lock.rb:15:in `call'
  actionpack (3.2.19) lib/action_dispatch/middleware/static.rb:63:in `call'
  rack-cache (1.2) lib/rack/cache/context.rb:136:in `forward'
  rack-cache (1.2) lib/rack/cache/context.rb:245:in `fetch'
  rack-cache (1.2) lib/rack/cache/context.rb:185:in `lookup'
  rack-cache (1.2) lib/rack/cache/context.rb:66:in `call!'
  rack-cache (1.2) lib/rack/cache/context.rb:51:in `call'
  railties (3.2.19) lib/rails/engine.rb:484:in `call'
  railties (3.2.19) lib/rails/application.rb:231:in `call'
  railties (3.2.19) lib/rails/railtie/configurable.rb:30:in `method_missing'
  passenger (4.0.46) lib/phusion_passenger/rack/out_of_band_gc.rb:47:in `call'
  passenger (4.0.46) lib/phusion_passenger/rack/thread_handler_extension.rb:74:in `process_request'
  passenger (4.0.46) lib/phusion_passenger/request_handler/thread_handler.rb:141:in `accept_and_process_next_request'
  passenger (4.0.46) lib/phusion_passenger/request_handler/thread_handler.rb:109:in `main_loop'
  passenger (4.0.46) lib/phusion_passenger/request_handler.rb:448:in `block (3 levels) in start_threads'

My environment 

This plug-in will be great for my organisation.
Thanks for your help

**Comment by Eric06** [comment]
Environment 
Environment:
  Redmine version                2.5.2.stable
  Ruby version                   2.0.0-p247 (2013-06-27) [x86_64-linux]
  Rails version                  3.2.19
  Environment                    integration
  Database adapter               PostgreSQL
SCM:
  Subversion                     1.8.8
  Filesystem                     
Redmine plugins:
  clipboard_image_paste          1.8
  my_projects                    1.3
  redmine_banner                 0.1.0
  redmine_default_assign         0.4
  redmine_extra_query_operators  0.1.2
  redmine_group_owners           1.0.0
  redmine_importer               1.2.2
  redmine_improved_searchbox     0.0.3
  redmine_issue_checklist        2.0.5
  redmine_issue_reminder         0.0.1
  redmine_issue_templates        0.0.9
  redmine_logs                   0.0.5
  redmine_mylyn_connector        2.8.3
  redmine_open_search            0.1.0
  redmine_passerelle_cap2        0.1.0
  redmine_restricted_members_managament 0.0.3
  redmine_wiki_extensions        0.6.5
  unread_issues                  0.0.1

**Comment by Eric06** [comment]
My fault. I installed bad version of plugin on my redmine. Closing the issue

**Comment by ppoektos** [comment]
Hi, I have exactly the same error in my redmine 2.6.0.
How to install the proper version?

**Comment by Eric06** [comment]
Hi there is a branch for 2.5 and 2.6 :https://github.com/Hopebaytech/redmine_issue_reminder/branches
I installed the package for 2.5 and hacing other trouble now. Don't know if 2.6 branches is working

**Comment by ppoektos** [comment]
I did
```
cd root_redmine
rake redmine:plugins:migrate NAME=redmine_issue_reminder VERSION=0 RAILS_ENV=production
cd ./plugins/redmine_issue_reminder
git branch -v -a
* master                    e44306c don't need this line
  remotes/origin/HEAD       -> origin/master
  remotes/origin/master     e44306c don't need this line
  remotes/origin/redmine2.0 2844719 Committing last changes of Célestin Matte and deleting strange files.
  remotes/origin/redmine2.5 ced6ce8 Update README.markdown
  remotes/origin/redmine2.6 f199bf9 Update README.markdown
git checkout redmine2.6
Branch redmine2.6 set up to track remote branch redmine2.6 from origin.
Switched to a new branch 'redmine2.6'
git branch -v -a
  master                    e44306c don't need this line
* redmine2.6                f199bf9 Update README.markdown
  remotes/origin/HEAD       -> origin/master
  remotes/origin/master     e44306c don't need this line
  remotes/origin/redmine2.0 2844719 Committing last changes of Célestin Matte and deleting strange files.
  remotes/origin/redmine2.5 ced6ce8 Update README.markdown
  remotes/origin/redmine2.6 f199bf9 Update README.markdown
rake redmine:plugins:migrate NAME=redmine_issue_reminder RAILS_ENV=production
```
And now at list reminder Tab works.

**Comment by Eric06** [comment]
Thanks for your feedback.
Unfortunatly, I can't use Git, only Zip Download. 
For now, didn't work on my Redmine. Still working ;-)

Errorlog : 
ActionView::Template::Error (undefined method `remote_function' for #<#<Class:0x007f7dfab5e0d0>:0x007f7dfab5d1a8>):
    7:   <p>
    8:     <%= f.label l(:interval) %>:
    9:     <%= f.select :interval, reminders_intervals_for_options, {},
    10:           {:onchange => remote_function(:url  => {:action => "update_interval_values"},
    11:               :with => "'interval='+value +'&reminder_id=#{reminder.new_record? ? 'new' : reminder.id}'")}
    12:     %>
    13:   </p>

**Comment by Eric06** [comment]
I installed the 2.6 branches and i can access to the list reminder Tab. But i can't save a task and i can't see reminder table in my database.

**Comment by Androc** [comment]
It means the database migrate command did not work.
Did you follow the installation instructions?
If you tried several installations, maybe there was a conflict and the
database believed it was installed while it is not
