### ISSUE TITLE
[Enhancement] Order of Queries in Email

### ISSUE THREAD

**Issue by soxyl** [Hopebaytech/redmine_issue_reminder#2]
It would be nice if the order of the queries in the email would be alphabetically (or some 'not technical' order). Currently they are ordered (ordered by id).

**Comment by jcppkkk** [comment]
The issue order should follow your redmine query setting, you can add up to 3 order rules at query setting page.

**Comment by Androc** [comment]
I think @soxyl found his answer a long time ago but did not update his issue :)
