### ISSUE TITLE
No Queries available

### ISSUE THREAD

**Issue by lordotter** [Hopebaytech/redmine_issue_reminder#27]
Hallo,
I installed redmine_issue_reminder out of branch 2.6.
My Redmine Version is 2.6.3

After installing it, enable it, I can't see any Queries. For sure I have open issues in my Project.
Does anybody have an idea to get it solved?

![issue_reminder](https://cloud.githubusercontent.com/assets/1105342/7276044/9df28dce-e907-11e4-9ead-a9f6d06162cd.png)

**Comment by Androc** [comment]
It is not a problem, read the issue #16, it is your solution :)

**Comment by lordotter** [comment]
Thanks. It works

**Comment by Androc** [comment]
You are welcome.
