### ISSUE TITLE
SPACE in the theme folder name

### ISSUE THREAD

**Issue by jsh562** [Hopebaytech/redmine_issue_reminder#28]
Using custom themes can cause issues with the email notification.

When you have a custom theme with a SPACE in the folder name
and then you run the rake command, errors appear. The first one is: "URI::InvalidURIError: bad URI<is not URI?>: /themes/xxx xxx/stylesheets/application.css"

I have done some testing and it turns out that the space in the folder name causes this issue (probably because of ruby). Changing the name of the folder to have no spaces corrected this issue for all of my custom themes.

**Comment by jcppkkk** [comment]
Hi @jsh562 , i think this is redmine's bug and have reported: http://www.redmine.org/issues/19791

You can keep using your theme without space folder name, or apply the patch to redmine code

http://www.redmine.org/attachments/13613/0001-URI-escape-stylesheet_link.patch

Thanks for report :smile:

**Comment by jsh562** [comment]
hmmm... I thought it would be more related to the plugin because I have used spaces in my theme folder names in Redmine v.2.4.0 thru v.2.6.0 and have not had any issues until I started using your plugin with Redmine v.3.0.2.

Thanks for the quick response!

**Comment by jcppkkk** [comment]
Added a patch to fix whitespace problem of Premailer

**Comment by jsh562** [comment]
Thanks for the quickness!
